PVI_Portafolio/PVI_Portafolio/Controllers/PortafolioController.cs
using PVI_Portafolio.Data;
using PVI_Portafolio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PVI_Portafolio.Controllers
{
    public class PortafolioController : Controller
    {
        // GET: Portafolio
        [HttpGet]
        public ActionResult MiPortafolio()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    return RedirectToAction("Login", "Registro");
                }

                int? id = (int)Session["Usuario"];
                UsuarioModel modelo = new UsuarioModel();

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    modelo = (from u in db.spConsultarUsuarioPorId(id)
                              select new UsuarioModel
                              {
                                  codigo = u.idUsuario,
                                  nombreCompleto = u.nombreCompleto,
                                  clave = u.clave,
                                  email = u.email,
                                  fechaNacimiento = u.fechaNacimiento
                              }).FirstOrDefault();

                    ViewBag.EstudiosRealizados = (from e in db.spConsultarEstudiosPorId(id)
                                                  select new EstudiosModel
                                                  {
                                                      idUsuario = e.idUsuario,
                                                      idEstudiosRealizados = e.idEstudioRealizado,
                                                      centroEducativo = e.centroEducativo,
                                                      tituloObtenido = e.titulo,
                                                      anhoFinalizacion = e.anhoFinalizacion
                                                  }).ToList();

                    ViewBag.ExperienciaLaboral = (from l in db.spConsultarExperienciaPorId(id)
                                                  select new ExperienciaModel
                                                  {
                                                      idUsuario = l.idUsuario,
                                                      idExpLaboral = l.idExperienciaLaboral,
                                                      nombreEmpresa = l.nombreEmpresa,
                                                      profesion = l.nombreProfesion,
                                                      fechaDesde = l.fechaDesde,
                                                      fechaHasta = l.fechaHasta
                                                  }).ToList();

                    ViewBag.Conocimientos = (from c in db.spConsultarConocimientosPorId(id)
                                             select new ConocimientosModel
                                             {
                                                 idUsuario = c.idUsuario,
                                                 idConocimiento = c.idConocimientoAdquirido,
                                                 anhoConocimientoAdquirido = c.anho,
                                                 descripcion = c.descripcion,
                                                 tipoMedio = c.tipoMedio
                                             }).ToList();

                    ViewBag.Referencias = (from r in db.spConsultarReferenciasPorId(id)
                                           select new ReferenciasModel
                                           {
                                               idUsuario = r.idUsuario,
                                               idReferencia = r.idReferencia,
                                               nombreRecomendacion = r.nombre,
                                               lugarTrabajo = r.lugarTrabajo,
                                               puesto = r.puesto,
                                               telefono = r.telefono
                                           }).ToList();

                }
                return View(modelo);
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpPost]
        public ActionResult Save_MiPortafolio(UsuarioModel modelo)
        {
            try
            {
                modelo.codigo = (int)Session["Usuario"];

                //Crear persistencia de datos
                if (!ModelState.IsValid)
                {
                    using (DataBaseEntities db = new DataBaseEntities())
                    {
                        ViewBag.EstudiosRealizados = (from e in db.spConsultarEstudiosPorId(modelo.codigo)
                                                      select new EstudiosModel
                                                      {
                                                          idUsuario = e.idUsuario,
                                                          idEstudiosRealizados = e.idEstudioRealizado,
                                                          centroEducativo = e.centroEducativo,
                                                          tituloObtenido = e.titulo,
                                                          anhoFinalizacion = e.anhoFinalizacion
                                                      }).ToList();

                        ViewBag.ExperienciaLaboral = (from l in db.spConsultarExperienciaPorId(modelo.codigo)
                                                      select new ExperienciaModel
                                                      {
                                                          idUsuario = l.idUsuario,
                                                          idExpLaboral = l.idExperienciaLaboral,
                                                          nombreEmpresa = l.nombreEmpresa,
                                                          profesion = l.nombreProfesion,
                                                          fechaDesde = l.fechaDesde,
                                                          fechaHasta = l.fechaHasta
                                                      }).ToList();

                        ViewBag.Conocimientos = (from c in db.spConsultarConocimientosPorId(modelo.codigo)
                                                 select new ConocimientosModel
                                                 {
                                                     idUsuario = c.idUsuario,
                                                     idConocimiento = c.idConocimientoAdquirido,
                                                     anhoConocimientoAdquirido = c.anho,
                                                     descripcion = c.descripcion,
                                                     tipoMedio = c.tipoMedio
                                                 }).ToList();

                        ViewBag.Referencias = (from r in db.spConsultarReferenciasPorId(modelo.codigo)
                                               select new ReferenciasModel
                                               {
                                                   idUsuario = r.idUsuario,
                                                   idReferencia = r.idReferencia,
                                                   nombreRecomendacion = r.nombre,
                                                   lugarTrabajo = r.lugarTrabajo,
                                                   puesto = r.puesto,
                                                   telefono = r.telefono
                                               }).ToList();

                    }

                    return View("MiPortafolio", modelo);
                }

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spEditarUsuario(modelo.codigo, modelo.nombreCompleto, modelo.fechaNacimiento);
                }

                TempData["Mensaje"] = "Los datos del usuario se editaron correctamente";
                return RedirectToAction("ExitoCrud", "Mensajes");
            }

            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }



        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                ConsultaModel modelo = new ConsultaModel();

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    //Llenado del DropdownList
                    var getProfesion = db.spConsultarTodosLasProfesiones().ToList();
                    SelectList lista = new SelectList(getProfesion, "idProfesion", "nombreProfesion");
                    ViewBag.ProfesionLista = lista;

                    ViewBag.Lista = (from t in db.spConsultaPublica02(modelo.nombre, modelo.idProfesion, modelo.edad)
                                     select new ConsultaListaModel
                                     {
                                         idUsuario = t.idUsuario,
                                         idProfesion = t.idProfesion,
                                         nombreCompleto = t.nombreCompleto,
                                         email = t.email,
                                         nombreProfesion = t.nombreProfesion,
                                         fechaNacimiento = t.fechaNacimiento
                                     }).ToList();

                }

                return View(modelo);//Se instancia el modelo vacio para presentarla en el Form
            }
            catch
            {

PVI_Portafolio/PVI_Portafolio/Views/Portafolio/Index.cshtml
@model PVI_Portafolio.Models.ConsultaModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@*Estilo CSS*@
<style type="text/css">
    .bs-example {
        margin: 20px;
    }
</style>

<h5>&nbsp;</h5>

<h1>@ViewBag.Prueba</h1>

@* Formulario para Consulta Pública*@
@using (Html.BeginForm("Index", "Portafolio", FormMethod.Post))
{
    <div class="container">
        <div class="row center-block">
            <div class="col-xs-12 col-sm-8 col-md-5 col-sm-offset-2 col-md-offset-3 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Consulta Pública</h3>
                    </div>

                    <div class="panel-body">
                        @Html.ValidationMessageFor(user => user.idProfesion, null, new { @class = "label label-danger" })
                        @Html.ValidationMessageFor(user => user.edad, null, new { @class = "label label-danger" })
                        <form role="form">
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        @*@Html.DropDownListFor(user => user.profesion, ViewBag.ProfesionLista as SelectList, "Profesión...", new { @class = "form-control input-sm" })*@
                                        @Html.DropDownListFor(user => user.idProfesion, ViewBag.ProfesionLista as SelectList, "Profesión...", new { @class = "form-control input-sm" })
                                        @*@Html.DropDownListFor(user => user.idProfesion, ViewBag.ProfesionLista ?? new List<SelectListItem>(), "Profesión...", new { @class = "form-control input-sm" })*@
                                        @*@Html.DropDownListFor(user => user.idProfesion, ViewBag.ProfesionLista as IEnumerable<SelectListItem>, new { @class = "form-control" })*@
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(user => user.edad, new { placeholder = "Ingrese edad", @class = "form-control input-sm" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.TextBoxFor(user => user.nombre, new { placeholder = "Nombre o Apellidos", @class = "form-control input-sm" })
                                @Html.ValidationMessageFor(user => user.nombre, null, new { @class = "label label-warning" })
                            </div>
                            <input type="submit" id="Buscar" value="Buscar" class="btn btn-primary" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*Se genera Tabla de Consulta Pública*@
<div class="bs-example">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nombre Completo</th>
                <th>Email</th>
                <th>Profesión</th>
                <th>Fecha Nacimiento</th>
                @*Hacer un espacio en blanco*@
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Lista != null)
            {
                foreach (PVI_Portafolio.Models.ConsultaListaModel fila in ViewBag.Lista)
                {
                    <tr>
                        <td>@fila.nombreCompleto</td>
                        <td>@fila.email</td>
                        <td>@fila.nombreProfesion</td>
                        <td>@fila.fechaNacimiento</td>
                        <td>
                            <a class="btn btn-primary" href="~/Portafolio/VerConsulta/@fila.idUsuario">Ver Registro</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>No hay Registros</td>
                </tr>
            }
        </tbody>
    </table>
</div>

PVI_Portafolio/PVI_Portafolio/Views/Portafolio/VerConsulta.cshtml
@model PVI_Portafolio.Models.UsuarioModel

@{
    ViewBag.Title = "VerConsulta";
    Layout = "~/Views/Shared/_LayoutPrivadoConsulta.cshtml";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<div class="container" style="margin-top: 20px;">
    @Html.ActionLink("Regresar", "Index", "Portafolio", null, new { @class = "btn btn-primary pull-right" })
    <div class="clearfix"></div>
</div>

@using (Html.BeginForm())
{
    @*Información Personal*@
    <div class="container" style="margin-top: 20px;">
        <div class="panel panel-primary">
            <div id="infoPersonal" class="panel-heading clickable">

                <h3 class="panel-title text-center"><span class="glyphicon glyphicon-user pull-left"></span>Información Personal</h3>
            </div>
            <div class="panel-body" style="margin-left: 12%;">
                <div class="row">
                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(user => user.codigo)
                            @Html.TextBoxFor(user => user.codigo, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(user => user.codigo, null, new { @class = "label label-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(user => user.email)
                            @Html.TextBoxFor(user => user.email, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(user => user.email, null, new { @class = "label label-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(user => user.nombreCompleto)
                            @Html.TextBoxFor(user => user.nombreCompleto, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(user => user.nombreCompleto, null, new { @class = "label label-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(user => user.fechaNacimiento)
                            @Html.EditorFor(user => user.fechaNacimiento, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(user => user.fechaNacimiento, null, new { @class = "label label-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*Estudios Realizados*@
<div class="container" style="margin-top: 20px;">

    <div class="panel panel-primary">
        <div id="estudios" class="panel-heading clickable">

            <h3 class="panel-title text-center"><span class="glyphicon glyphicon-education pull-left"></span>Estudios Realizados</h3>
        </div>
        <div class="panel-body" style="margin-left: 3%">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre del Centro Educativo</th>
                        <th>Titulo Obtenido</th>
                        <th>Año Finalización</th>
                        @*<th>&nbsp;</th>*@
                    </tr>
                </thead>
                <tbody>
                    @foreach (PVI_Portafolio.Models.EstudiosModel fila in ViewBag.EstudiosRealizados)
                    {
                        <tr>
                            <td>@fila.centroEducativo</td>
                            <td>@fila.tituloObtenido</td>
                            <td>@fila.anhoFinalizacion</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@*Experiencia Laboral*@
<div class="container" style="margin-top: 20px;">
    <div class="panel panel-primary">
        <div id="expLaboral" class="panel-heading clickable">

            <h3 class="panel-title text-center"><span class="glyphicon glyphicon-briefcase pull-left"></span>Experiencia Laboral</h3>
        </div>
        <div class="panel-body" style="margin-left: 3%">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Empresa</th>
                        <th>Profesión</th>
                        <th>Desde</th>
                        <th>Hasta</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (PVI_Portafolio.Models.ExperienciaModel fila in ViewBag.ExperienciaLaboral)
                    {
                        <tr>
                            <td>@fila.nombreEmpresa</td>
                            <td>@fila.profesion</td>
                            <td>@fila.fechaDesde</td>
                            <td>@fila.fechaHasta</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

@*Conocimientos Adquiridos*@
<div class="container" style="margin-top: 20px;">
    <div class="panel panel-primary">
        <div id="conocimientos" class="panel-heading clickable">
            <h3 class="panel-title text-center"><span class="glyphicon glyphicon-book pull-left"></span>Conocimientos Adquiridos</h3>
        </div>
        <div class="panel-body" style="margin-left: 3%">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Año</th>
                        <th>Descripción</th>
                        <th>Medio de Aprendizaje</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (PVI_Portafolio.Models.ConocimientosModel fila in ViewBag.Conocimientos)
                    {
                        <tr>
                            <td>@fila.anhoConocimientoAdquirido</td>
                            <td>@fila.descripcion</td>
                            <td>@fila.tipoMedio</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@*Recomendaciones*@
<div class="container" style="margin-top: 20px;">
    <div class="panel panel-primary">
        <div id="recomendaciones" class="panel-heading clickable">
            <h3 class="panel-title text-center"><span class="glyphicon glyphicon-file pull-left"></span>Recomendaciones</h3>
        </div>
        <div class="panel-body" style="margin-left: 3%">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Compañía</th>
                        <th>Puesto</th>
                        <th>Teléfono</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (PVI_Portafolio.Models.ReferenciasModel fila in ViewBag.Referencias)
                    {
                        <tr>
                            <td>@fila.nombreRecomendacion</td>
                            <td>@fila.lugarTrabajo</td>
                            <td>@fila.puesto</td>
                            <td>@fila.telefono</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>