PVI_Portafolio/PVI_Portafolio/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVI_Portafolio.Data;
using PVI_Portafolio.Models;

namespace PVI_Portafolio.Controllers
{
    public class CrudController : Controller
    {
        [HttpGet]
        public ActionResult EditarEstudios(int id)
        {
            try
            {
                EstudiosModel modelo = null;

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    modelo = (from e in db.spConsultarEstudiosPorId02(id)
                              select new EstudiosModel
                              {
                                  idUsuario = e.idUsuario,
                                  idEstudiosRealizados = e.idEstudioRealizado,
                                  anhoFinalizacion = e.anhoFinalizacion,
                                  centroEducativo = e.centroEducativo,
                                  tituloObtenido = e.titulo
                              }).FirstOrDefault();
                }

                return View(modelo);
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpPost]
        public ActionResult EditarEstudios(EstudiosModel modelo)
        {
            try
            {
                //Crear persistencia de datos
                if (!ModelState.IsValid)
                {
                    return View(modelo);
                }

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spEditarEstudiosRealizados02(
                        modelo.idUsuario,
                        modelo.idEstudiosRealizados,
                        modelo.anhoFinalizacion,
                        modelo.tituloObtenido,
                        modelo.centroEducativo
                        );
                }

                TempData["Mensaje"] = "Los datos del usuario se editaron correctamente";
                return RedirectToAction("ExitoCrud", "Mensajes");

            }
            catch
            {
                TempData["Mensaje"] = "Error de conexión con la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpGet]
        public ActionResult EliminarEstudios(int id)
        {
            try
            {
                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spEliminarEstudiosRealizados(id);
                }

                TempData["EliminarMensaje"] = "Los datos del formulario se eliminaron correctamente";
                return RedirectToAction("MiPortafolio", "Portafolio");
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpGet]
        public ActionResult AgregarEstudios()
        {
            try
            {
                int id = (int)Session["Usuario"];

                return View(new EstudiosModel());//Se instancia el modelo vacio para presentarla en el Form
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpPost]
        public ActionResult AgregarEstudios(EstudiosModel modelo)
        {
            try
            {
                modelo.idUsuario = (int)Session["Usuario"];

                //Crear persistencia de datos
                if (!ModelState.IsValid)
                {
                    return View(modelo);
                }

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spCrearEstudiosRealizados(
                        modelo.idUsuario,
                        modelo.anhoFinalizacion,
                        modelo.tituloObtenido,
                        modelo.centroEducativo,
                        DateTime.Now
                        );
                }

                TempData["Mensaje"] = "Se ha agregado el registro correctamente";
                return RedirectToAction("ExitoCrud", "Mensajes");
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }

        }

        [HttpGet]
        public ActionResult EditarExpLaboral(int id)
        {
            try
            {
                ExperienciaModel modelo = null;

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    //Llenado del DropdownList
                    var getProfesion = db.spConsultarTodosLasProfesiones().ToList();
                    SelectList lista = new SelectList(getProfesion, "idProfesion", "nombreProfesion");
                    ViewBag.ProfesionLista = lista;

                    modelo = (from l in db.spConsultarExperienciaPorId03(id)
                              select new ExperienciaModel
                              {
                                  idUsuario = l.idUsuario,
                                  idExpLaboral = l.idExperienciaLaboral,
                                  nombreEmpresa = l.nombreEmpresa,
                                  fechaDesde = l.fechaDesde,
                                  fechaHasta = l.fechaHasta,
                                  idProfesion = l.idProfesion
                              }).FirstOrDefault();
                }

                return View(modelo);
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpPost]
        public ActionResult EditarExpLaboral(ExperienciaModel modelo)
        {
            try
            {
                //Crear persistencia de datos
                if (!ModelState.IsValid)
                {
                    return View(modelo);
                }

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spEditarExpLaboral(
                        modelo.idUsuario,
                        modelo.idExpLaboral,
                        modelo.idProfesion,
                        modelo.nombreEmpresa,
                        modelo.fechaDesde,
                        modelo.fechaHasta
                        );
                }

                TempData["Mensaje"] = "Los datos del usuario se editaron correctamente";
                return RedirectToAction("ExitoCrud", "Mensajes");

            }
            catch
            {
                TempData["Mensaje"] = "Error de conexión con la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpGet]
        public ActionResult AgregarExpLaboral()
        {
            try
            {
                int id = (int)Session["Usuario"];

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    //Llenado del DropdownList
                    var getProfesion = db.spConsultarTodosLasProfesiones().ToList();
                    SelectList lista = new SelectList(getProfesion, "idProfesion", "nombreProfesion");
                    ViewBag.ProfesionLista = lista;

                }

                return View(new ExperienciaModel());//Se instancia el modelo vacio para presentarla en el Form
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }
        }

        [HttpPost]
        public ActionResult AgregarExpLaboral(ExperienciaModel modelo)
        {
            try
            {
                modelo.idUsuario = (int)Session["Usuario"];

                //Crear persistencia de datos
                if (!ModelState.IsValid)
                {
                    using (DataBaseEntities db = new DataBaseEntities())
                    {
                        //Llenado del DropdownList
                        var getProfesion = db.spConsultarTodosLasProfesiones().ToList();
                        SelectList lista = new SelectList(getProfesion, "idProfesion", "nombreProfesion");
                        ViewBag.ProfesionLista = lista;

                    }

                    return View(modelo);
                }

                using (DataBaseEntities db = new DataBaseEntities())
                {
                    db.spCrearExperienciaLaboral(
                        modelo.idUsuario,
                        modelo.idProfesion,
                        modelo.nombreEmpresa,
                        modelo.fechaDesde,
                        modelo.fechaHasta,
                        DateTime.Now
                        );
                }

                TempData["Mensaje"] = "Se ha creado el registro para el usuario";
                return RedirectToAction("ExitoCrud", "Mensajes");
            }
            catch
            {
                TempData["Mensaje"] = "Se ha generado un error al consultar la Base de Datos";
                return RedirectToAction("ErrorRegistro", "Mensajes");
            }

        }

        [HttpGet]
        public ActionResult EliminarExpLaboral(int id)
        {
            try
            {
                using (DataBaseEntities db = new DataBaseEntities())
                {

PVI_Portafolio/PVI_Portafolio/Views/Crud/AgregarConocimientos.cshtml
@model PVI_Portafolio.Models.ConocimientosModel

@{
    ViewBag.Title = "AgregarConocimientos";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("AgregarConocimientos", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Conocimientos Adquiridos
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.anhoConocimientoAdquirido)
                            @Html.TextBoxFor(user => user.anhoConocimientoAdquirido, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.anhoConocimientoAdquirido, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.descripcion)
                            @Html.TextAreaFor(user => user.descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.descripcion, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.tipoMedio)
                            @Html.TextBoxFor(user => user.tipoMedio, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.tipoMedio, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

PVI_Portafolio/PVI_Portafolio/Views/Crud/AgregarEstudios.cshtml
@model PVI_Portafolio.Models.EstudiosModel

@{
    ViewBag.Title = "AgregarEstudios";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("AgregarEstudios", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Estudios Realizados
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.anhoFinalizacion)
                            @Html.TextBoxFor(user => user.anhoFinalizacion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.anhoFinalizacion, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.tituloObtenido)
                            @Html.TextBoxFor(user => user.tituloObtenido, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.tituloObtenido, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.centroEducativo)
                            @Html.TextBoxFor(user => user.centroEducativo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.centroEducativo, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

PVI_Portafolio/PVI_Portafolio/Views/Crud/AgregarExpLaboral.cshtml
@model PVI_Portafolio.Models.ExperienciaModel

@{
    ViewBag.Title = "AgregarExpLaboral";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("AgregarExpLaboral", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Experiencia Laboral
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.nombreEmpresa)
                            @Html.TextBoxFor(user => user.nombreEmpresa, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.nombreEmpresa, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.fechaDesde)
                            @Html.EditorFor(user => user.fechaDesde, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(user => user.fechaDesde, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.fechaHasta)
                            @*@Html.TextBoxFor(user => user.fechaHasta, new { htmlAttributes = new { @class = "datepicker" } })*@
                            @Html.EditorFor(user => user.fechaHasta, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(user => user.fechaHasta, null, new { @class = "label label-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(user => user.idProfesion)
                            @Html.DropDownListFor(user => user.idProfesion, ViewBag.ProfesionLista as SelectList, "Profesión...", new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(user => user.idProfesion, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $.datepicker.regional['es'] = {
                closeText: 'Cerrar',
                prevText: '< Ant',
                nextText: 'Sig >',
                currentText: 'Hoy',
                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
                dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
                weekHeader: 'Sm',
                dateFormat: 'dd/mm/yy',
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['es']);

            $(function () {
                $("#fechaHasta").datepicker({
                    dateFormat: "dd/mm/yy",
                    changeMonth: true,
                    changeYear: true,
                    //yearRange : "-10:+10"
                    //minDate: new Date(1950, 0, 1),
                    maxDate: new Date(2021, 0, 1),
                    //showOn: "both",
                    //buttonText : "<i class='fa fa-calendar'></i>"
                });

                $("#fechaDesde").datepicker({
                    dateFormat: "dd/mm/yy",
                    changeMonth: true,
                    changeYear: true,
                    maxDate: new Date(2021, 0, 1),
                });
        });

        });
    </script>

}

PVI_Portafolio/PVI_Portafolio/Views/Crud/AgregarReferencias.cshtml
@model PVI_Portafolio.Models.ReferenciasModel

@{
    ViewBag.Title = "AgregarReferencias";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("AgregarReferencias", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Recomendaciones
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.nombreRecomendacion)
                            @Html.TextBoxFor(user => user.nombreRecomendacion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.nombreRecomendacion, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.lugarTrabajo)
                            @Html.TextBoxFor(user => user.lugarTrabajo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.lugarTrabajo, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.puesto)
                            @Html.TextBoxFor(user => user.puesto, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.puesto, null, new { @class = "label label-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(user => user.telefono)
                            @Html.TextBoxFor(user => user.telefono, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.telefono, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

PVI_Portafolio/PVI_Portafolio/Views/Crud/EditarConocimientos.cshtml
@model PVI_Portafolio.Models.ConocimientosModel

@{
    ViewBag.Title = "EditarConocimientos";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("EditarConocimientos", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
        @Html.HiddenFor(user => user.idConocimiento)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Conocimientos Adquiridos
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.anhoConocimientoAdquirido)
                            @Html.TextBoxFor(user => user.anhoConocimientoAdquirido, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.anhoConocimientoAdquirido, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.descripcion)
                            @Html.TextAreaFor(user => user.descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.descripcion, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.tipoMedio)
                            @Html.TextBoxFor(user => user.tipoMedio, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.tipoMedio, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

PVI_Portafolio/PVI_Portafolio/Views/Crud/EditarEstudios.cshtml
@model PVI_Portafolio.Models.EstudiosModel 

@{
    ViewBag.Title = "EditarEstudios";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("EditarEstudios", "Crud", FormMethod.Post))
{
<div>
    @Html.HiddenFor(user => user.idUsuario)
    @Html.HiddenFor(user => user.idEstudiosRealizados)
</div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Estudios Realizados
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.anhoFinalizacion)
                            @Html.TextBoxFor(user => user.anhoFinalizacion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.anhoFinalizacion, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.tituloObtenido)
                            @Html.TextBoxFor(user => user.tituloObtenido, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.tituloObtenido, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.centroEducativo)
                            @Html.TextBoxFor(user => user.centroEducativo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.centroEducativo, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

PVI_Portafolio/PVI_Portafolio/Views/Crud/EditarExpLaboral.cshtml
@model PVI_Portafolio.Models.ExperienciaModel

@{
    ViewBag.Title = "EditarExpLaboral";
    Layout = "~/Views/Shared/_LayoutPrivado.cshtml";
}

@using (Html.BeginForm("EditarExpLaboral", "Crud", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(user => user.idUsuario)
        @Html.HiddenFor(user => user.idExpLaboral)
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6 col-sm-12 col-lg-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Experiencia Laboral
                </div>
                <div class="panel-body">
                    <form name="myform">
                        <div class="form-group">
                            @Html.LabelFor(user => user.nombreEmpresa)
                            @Html.TextBoxFor(user => user.nombreEmpresa, new { @class = "form-control" })
                            @Html.ValidationMessageFor(user => user.nombreEmpresa, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.fechaDesde)
                            @Html.EditorFor(user => user.fechaDesde, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(user => user.fechaDesde, null, new { @class = "label label-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(user => user.fechaHasta)
                            @*@Html.TextBoxFor(user => user.fechaHasta, new { htmlAttributes = new { @class = "datepicker" } })*@
                            @Html.EditorFor(user => user.fechaHasta, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(user => user.fechaHasta, null, new { @class = "label label-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(user => user.idProfesion)
                            @Html.DropDownListFor(user => user.idProfesion, ViewBag.ProfesionLista as SelectList, "Profesión...", new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(user => user.idProfesion, null, new { @class = "label label-danger" })
                        </div>

                        <div class="col-lg-12">
                            <input type="submit" id="Guardar" value="Guardar" class="btn btn-primary" />
                            @Html.ActionLink("Cancelar", "MiPortafolio", "Portafolio", null, new { @class = "btn btn-default" })
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {

            $.datepicker.regional['es'] = {
                closeText: 'Cerrar',
                prevText: '< Ant',
                nextText: 'Sig >',
                currentText: 'Hoy',
                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
                dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
                weekHeader: 'Sm',
                dateFormat: 'dd/mm/yy',
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['es']);

            $(function () {
                $("#fechaHasta").datepicker({
                    dateFormat: "dd/mm/yy",
                    changeMonth: true,
                    changeYear: true,
                    //yearRange : "-10:+10"
                    //minDate: new Date(1950, 0, 1),
                    maxDate: new Date(2021, 0, 1),
                    //showOn: "both",
                    //buttonText : "<i class='fa fa-calendar'></i>"
                });

                $("#fechaDesde").datepicker({
                    dateFormat: "dd/mm/yy",
                    changeMonth: true,
                    changeYear: true,
                    maxDate: new Date(2021, 0, 1),
                });
        });

        });
    </script>

}